GSK3B+JNK3-PPO:
  Agent:
    type: PPO
    n_steps: 64
    epoch: 6
    seq_len: 35
    seq_mini_batch_size: 16
    gamma: 1.0
  Env:
    gsk3b_coef: 0.5
    jnk3_coef: 0.5
  Train:
    num_envs: 64
    seed: 0
    total_time_steps: 120000
    summary_freq: 1000
    device: cuda
