GSK3B_JNK3-PPO:
  Agent:
    device: cuda
    entropy_coef: 0.001
    epoch: 6
    gamma: 1.0
    n_steps: 64
    seq_len: 35
    seq_mini_batch_size: 16
    type: RecurrentPPO
  Env:
    max_str_len: 35
    gsk3b_coef: 0.5
    jnk3_coef: 0.5
  Train:
    num_envs: 64
    seed: 0
    summary_freq: 1000
    time_steps: 120000
