QED-CountRND_0.001_1.0:
  Agent:
    device: cuda
    entropy_coef: 0.001
    epoch: 6
    ext_gamma: 1.0
    int_adv_coef: 1.0
    n_steps: 64
    seq_len: 35
    seq_mini_batch_size: 16
    type: RecurrentPPORND
  Env:
    count_coef: 0.001
    max_str_len: 35
    qed_coef: 1.0
  Train:
    num_envs: 64
    seed: 0
    summary_freq: 1000
    time_steps: 120000
